[start]
runImage = "ghcr.io/railwayapp/nixpacks:debian-12"
onlyIncludeFiles = [
  "app",
  "bootstrap",
  "config",
  "database",
  "public",
  "resources",
  "routes",
  "storage",
  "vendor",
  "artisan",
  "composer.json",
  "composer.lock",
  "package.json",
  ".env.example",
  "php",
  "phpunit.xml"
]
